# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dfranx/Desktop/projs/ShaderDebugger

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dfranx/Desktop/projs/ShaderDebugger

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dfranx/Desktop/projs/ShaderDebugger/CMakeFiles /home/dfranx/Desktop/projs/ShaderDebugger/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dfranx/Desktop/projs/ShaderDebugger/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ShaderDebugger

# Build rule for target.
ShaderDebugger: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ShaderDebugger
.PHONY : ShaderDebugger

# fast build rule for target.
ShaderDebugger/fast:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/build
.PHONY : ShaderDebugger/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ContinuousSubmit.dir/build.make libs/glslang/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ContinuousCoverage.dir/build.make libs/glslang/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ContinuousTest.dir/build.make libs/glslang/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ContinuousBuild.dir/build.make libs/glslang/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ContinuousMemCheck.dir/build.make libs/glslang/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/Nightly.dir/build.make libs/glslang/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlyTest.dir/build.make libs/glslang/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/Continuous.dir/build.make libs/glslang/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlyUpdate.dir/build.make libs/glslang/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlyMemCheck.dir/build.make libs/glslang/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlyMemoryCheck.dir/build.make libs/glslang/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlyStart.dir/build.make libs/glslang/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlyBuild.dir/build.make libs/glslang/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ExperimentalStart.dir/build.make libs/glslang/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ExperimentalConfigure.dir/build.make libs/glslang/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ExperimentalCoverage.dir/build.make libs/glslang/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ExperimentalBuild.dir/build.make libs/glslang/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlyConfigure.dir/build.make libs/glslang/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ExperimentalTest.dir/build.make libs/glslang/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ExperimentalMemCheck.dir/build.make libs/glslang/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/Experimental.dir/build.make libs/glslang/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlySubmit.dir/build.make libs/glslang/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ExperimentalSubmit.dir/build.make libs/glslang/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ContinuousStart.dir/build.make libs/glslang/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ContinuousUpdate.dir/build.make libs/glslang/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/NightlyCoverage.dir/build.make libs/glslang/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ExperimentalUpdate.dir/build.make libs/glslang/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f libs/glslang/CMakeFiles/ContinuousConfigure.dir/build.make libs/glslang/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named glslang

# Build rule for target.
glslang: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glslang
.PHONY : glslang

# fast build rule for target.
glslang/fast:
	$(MAKE) -f libs/glslang/glslang/CMakeFiles/glslang.dir/build.make libs/glslang/glslang/CMakeFiles/glslang.dir/build
.PHONY : glslang/fast

#=============================================================================
# Target rules for targets named OSDependent

# Build rule for target.
OSDependent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OSDependent
.PHONY : OSDependent

# fast build rule for target.
OSDependent/fast:
	$(MAKE) -f libs/glslang/glslang/OSDependent/Unix/CMakeFiles/OSDependent.dir/build.make libs/glslang/glslang/OSDependent/Unix/CMakeFiles/OSDependent.dir/build
.PHONY : OSDependent/fast

#=============================================================================
# Target rules for targets named OGLCompiler

# Build rule for target.
OGLCompiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OGLCompiler
.PHONY : OGLCompiler

# fast build rule for target.
OGLCompiler/fast:
	$(MAKE) -f libs/glslang/OGLCompilersDLL/CMakeFiles/OGLCompiler.dir/build.make libs/glslang/OGLCompilersDLL/CMakeFiles/OGLCompiler.dir/build
.PHONY : OGLCompiler/fast

#=============================================================================
# Target rules for targets named SPIRV

# Build rule for target.
SPIRV: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SPIRV
.PHONY : SPIRV

# fast build rule for target.
SPIRV/fast:
	$(MAKE) -f libs/glslang/SPIRV/CMakeFiles/SPIRV.dir/build.make libs/glslang/SPIRV/CMakeFiles/SPIRV.dir/build
.PHONY : SPIRV/fast

#=============================================================================
# Target rules for targets named HLSL

# Build rule for target.
HLSL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HLSL
.PHONY : HLSL

# fast build rule for target.
HLSL/fast:
	$(MAKE) -f libs/glslang/hlsl/CMakeFiles/HLSL.dir/build.make libs/glslang/hlsl/CMakeFiles/HLSL.dir/build
.PHONY : HLSL/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/main.cpp.s
.PHONY : main.cpp.s

src/BVMGenerator.o: src/BVMGenerator.cpp.o

.PHONY : src/BVMGenerator.o

# target to build an object file
src/BVMGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/BVMGenerator.cpp.o
.PHONY : src/BVMGenerator.cpp.o

src/BVMGenerator.i: src/BVMGenerator.cpp.i

.PHONY : src/BVMGenerator.i

# target to preprocess a source file
src/BVMGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/BVMGenerator.cpp.i
.PHONY : src/BVMGenerator.cpp.i

src/BVMGenerator.s: src/BVMGenerator.cpp.s

.PHONY : src/BVMGenerator.s

# target to generate assembly for a file
src/BVMGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/BVMGenerator.cpp.s
.PHONY : src/BVMGenerator.cpp.s

src/ShaderConverter.o: src/ShaderConverter.cpp.o

.PHONY : src/ShaderConverter.o

# target to build an object file
src/ShaderConverter.cpp.o:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/ShaderConverter.cpp.o
.PHONY : src/ShaderConverter.cpp.o

src/ShaderConverter.i: src/ShaderConverter.cpp.i

.PHONY : src/ShaderConverter.i

# target to preprocess a source file
src/ShaderConverter.cpp.i:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/ShaderConverter.cpp.i
.PHONY : src/ShaderConverter.cpp.i

src/ShaderConverter.s: src/ShaderConverter.cpp.s

.PHONY : src/ShaderConverter.s

# target to generate assembly for a file
src/ShaderConverter.cpp.s:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/ShaderConverter.cpp.s
.PHONY : src/ShaderConverter.cpp.s

src/ShaderDebugger.o: src/ShaderDebugger.cpp.o

.PHONY : src/ShaderDebugger.o

# target to build an object file
src/ShaderDebugger.cpp.o:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/ShaderDebugger.cpp.o
.PHONY : src/ShaderDebugger.cpp.o

src/ShaderDebugger.i: src/ShaderDebugger.cpp.i

.PHONY : src/ShaderDebugger.i

# target to preprocess a source file
src/ShaderDebugger.cpp.i:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/ShaderDebugger.cpp.i
.PHONY : src/ShaderDebugger.cpp.i

src/ShaderDebugger.s: src/ShaderDebugger.cpp.s

.PHONY : src/ShaderDebugger.s

# target to generate assembly for a file
src/ShaderDebugger.cpp.s:
	$(MAKE) -f CMakeFiles/ShaderDebugger.dir/build.make CMakeFiles/ShaderDebugger.dir/src/ShaderDebugger.cpp.s
.PHONY : src/ShaderDebugger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... ShaderDebugger"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... NightlyTest"
	@echo "... Continuous"
	@echo "... NightlyUpdate"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlyBuild"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousStart"
	@echo "... ContinuousUpdate"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousConfigure"
	@echo "... glslang"
	@echo "... OSDependent"
	@echo "... OGLCompiler"
	@echo "... SPIRV"
	@echo "... HLSL"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/BVMGenerator.o"
	@echo "... src/BVMGenerator.i"
	@echo "... src/BVMGenerator.s"
	@echo "... src/ShaderConverter.o"
	@echo "... src/ShaderConverter.i"
	@echo "... src/ShaderConverter.s"
	@echo "... src/ShaderDebugger.o"
	@echo "... src/ShaderDebugger.i"
	@echo "... src/ShaderDebugger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

